

function ifErrorDoThis()  {
  console.log("예외가 발생했습니다.")
}

function throwError() {
  throw new Error("예외를 던질것입니다.")
}

describe("예외처리 연습을 진행합니다." ,() =>{
  test("")
})